-- =============================================================================
-- Movimientos de inventario
-- Todo cambio de stock es un DOCUMENTO (entrada, salida o ajuste) con sus líneas.
-- Las líneas son el kardex: cantidad con signo en unidad base y saldo resultante.
-- =============================================================================

create type public.doc_kind as enum ('entrada', 'salida', 'ajuste');
create type public.doc_reason as enum (
  'compra', 'inventario_inicial', 'devolucion_cliente',            -- entradas
  'venta', 'consumo_interno', 'merma', 'devolucion_proveedor',       -- salidas
  'conteo', 'otro');

create table public.stock_doc (
  id uuid primary key default gen_random_uuid(),
  number bigint generated by default as identity (start with 1) unique,
  kind public.doc_kind not null,
  reason public.doc_reason not null,
  supplier_id uuid references public.supplier (id) on delete set null,
  party text,                        -- cliente, obra o destino (salidas)
  reference text,                    -- factura, guía, boleta
  note text,
  line_count int not null default 0,
  total_cost numeric(14, 2) not null default 0,    -- valorizado a costo
  total_price numeric(14, 2) not null default 0,   -- valorizado a precio (salidas por venta)
  user_id uuid references auth.users (id) on delete set null,
  created_at timestamptz not null default now(),
  voided_at timestamptz,
  voided_by uuid references auth.users (id) on delete set null,
  void_reason text
);
create index stock_doc_created_idx on public.stock_doc (created_at desc);

create table public.stock_movement (
  id uuid primary key default gen_random_uuid(),
  doc_id uuid not null references public.stock_doc (id) on delete cascade,
  product_id uuid not null references public.product (id) on delete cascade,
  quantity numeric(14, 3) not null,     -- + entra, − sale (unidad base)
  balance numeric(14, 3) not null,      -- stock del producto después del movimiento
  unit_cost numeric(12, 4) not null default 0,
  unit_price numeric(12, 4),            -- precio por unidad base (salidas)
  entered_quantity numeric(14, 3),      -- lo que se digitó (p. ej. 2 rollos)
  entered_unit text,                    -- 'rollo', 'm'…
  created_at timestamptz not null default now()
);
create index stock_movement_product_idx on public.stock_movement (product_id, created_at desc);
create index stock_movement_doc_idx on public.stock_movement (doc_id);

-- -----------------------------------------------------------------------------
-- Aplica una línea: bloquea el producto, valida stock, actualiza costo promedio y registra el kardex.
-- -----------------------------------------------------------------------------
create or replace function internal.apply_line(p_doc public.stock_doc, p_product uuid, p_qty numeric, p_unit_cost numeric,
                                              p_unit_price numeric, p_entered_qty numeric, p_entered_unit text)
returns public.stock_movement language plpgsql as $$
declare
  v_prod public.product;
  v_new numeric;
  v_cost numeric;
  v_mov public.stock_movement;
begin
  select * into v_prod from public.product where id = p_product for update;
  if v_prod.id is null then raise exception 'Producto no encontrado'; end if;
  if p_qty = 0 then raise exception 'La cantidad de % no puede ser cero', v_prod.name; end if;
  v_new := v_prod.stock + p_qty;
  if v_new < 0 and not coalesce((select allow_negative_stock from public.business limit 1), false) then
    raise exception 'Stock insuficiente de %: hay % %', v_prod.name, trim(to_char(v_prod.stock, 'FM999999990.###')), v_prod.unit;
  end if;

  v_cost := v_prod.cost;
  if p_qty > 0 and p_doc.kind = 'entrada' and p_unit_cost is not null then
    -- Costo promedio ponderado (el stock negativo no pesa).
    v_cost := round((greatest(v_prod.stock, 0) * v_prod.cost + p_qty * p_unit_cost) / nullif(greatest(v_prod.stock, 0) + p_qty, 0), 4);
  end if;

  perform set_config('app.stock_rpc', 'on', true);
  update public.product set stock = v_new, cost = coalesce(v_cost, cost) where id = p_product;
  perform set_config('app.stock_rpc', 'off', true);

  insert into public.stock_movement (doc_id, product_id, quantity, balance, unit_cost, unit_price, entered_quantity, entered_unit, created_at)
  values (p_doc.id, p_product, p_qty, v_new, coalesce(case when p_qty > 0 and p_doc.kind = 'entrada' then p_unit_cost end, v_prod.cost),
          p_unit_price, p_entered_qty, p_entered_unit, p_doc.created_at)
  returning * into v_mov;
  return v_mov;
end $$;

create or replace function internal.close_doc(p_doc uuid) returns public.stock_doc language sql as $$
  update public.stock_doc d set
    line_count = (select count(*) from public.stock_movement m where m.doc_id = d.id),
    total_cost = (select coalesce(round(sum(abs(m.quantity) * m.unit_cost), 2), 0) from public.stock_movement m where m.doc_id = d.id),
    total_price = (select coalesce(round(sum(abs(m.quantity) * coalesce(m.unit_price, 0)), 2), 0) from public.stock_movement m where m.doc_id = d.id)
  where d.id = p_doc
  returning *
$$;

-- Convierte lo digitado a unidad base: {quantity, unit: 'base'|'pack'}.
create or replace function internal.to_base(p_prod public.product, p_qty numeric, p_unit text) returns numeric language sql immutable as $$
  select p_qty * case when p_unit = 'pack' then p_prod.pack_size else 1 end
$$;

-- -----------------------------------------------------------------------------
-- Entrada (compra, inventario inicial, devolución de cliente)
-- p: { reason?, supplier_id?, reference?, note?, created_at? (solo seed), items: [{ product_id, quantity, unit: 'base'|'pack', unit_cost? (por unidad digitada) }] }
-- -----------------------------------------------------------------------------
create or replace function internal.register_entry(p jsonb, p_user uuid) returns public.stock_doc language plpgsql as $$
declare
  v_doc public.stock_doc;
  v_item jsonb;
  v_prod public.product;
  v_unit text;
  v_factor numeric;
begin
  if jsonb_array_length(coalesce(p->'items', '[]')) = 0 then raise exception 'La entrada no tiene productos'; end if;
  insert into public.stock_doc (kind, reason, supplier_id, reference, note, user_id, created_at)
  values ('entrada', coalesce(nullif(p->>'reason', ''), 'compra')::public.doc_reason, nullif(p->>'supplier_id', '')::uuid,
          nullif(trim(p->>'reference'), ''), nullif(trim(p->>'note'), ''), p_user, coalesce((p->>'created_at')::timestamptz, now()))
  returning * into v_doc;
  if v_doc.reason not in ('compra', 'inventario_inicial', 'devolucion_cliente', 'otro') then raise exception 'Motivo de entrada inválido'; end if;

  for v_item in select * from jsonb_array_elements(p->'items') loop
    select * into v_prod from public.product where id = (v_item->>'product_id')::uuid;
    if v_prod.id is null then raise exception 'Producto no encontrado'; end if;
    v_unit := coalesce(nullif(v_item->>'unit', ''), 'base');
    v_factor := case when v_unit = 'pack' then v_prod.pack_size else 1 end;
    if coalesce((v_item->>'quantity')::numeric, 0) <= 0 then raise exception 'Cantidad inválida para %', v_prod.name; end if;
    perform internal.apply_line(v_doc, v_prod.id, (v_item->>'quantity')::numeric * v_factor,
      case when nullif(v_item->>'unit_cost', '') is null then v_prod.cost else (v_item->>'unit_cost')::numeric / v_factor end,
      null, (v_item->>'quantity')::numeric, case when v_unit = 'pack' then v_prod.pack_unit else v_prod.unit end);
  end loop;
  return internal.close_doc(v_doc.id);
end $$;

-- -----------------------------------------------------------------------------
-- Salida (venta, consumo interno, merma, devolución a proveedor)
-- p: { reason, party?, reference?, note?, items: [{ product_id, quantity, unit: 'base'|'pack', unit_price? (por unidad digitada) }] }
-- -----------------------------------------------------------------------------
create or replace function internal.register_exit(p jsonb, p_user uuid) returns public.stock_doc language plpgsql as $$
declare
  v_doc public.stock_doc;
  v_item jsonb;
  v_prod public.product;
  v_unit text;
  v_factor numeric;
  v_price numeric;
begin
  if jsonb_array_length(coalesce(p->'items', '[]')) = 0 then raise exception 'La salida no tiene productos'; end if;
  insert into public.stock_doc (kind, reason, supplier_id, party, reference, note, user_id, created_at)
  values ('salida', coalesce(nullif(p->>'reason', ''), 'venta')::public.doc_reason, nullif(p->>'supplier_id', '')::uuid, nullif(trim(p->>'party'), ''),
          nullif(trim(p->>'reference'), ''), nullif(trim(p->>'note'), ''), p_user, coalesce((p->>'created_at')::timestamptz, now()))
  returning * into v_doc;
  if v_doc.reason not in ('venta', 'consumo_interno', 'merma', 'devolucion_proveedor', 'otro') then raise exception 'Motivo de salida inválido'; end if;

  for v_item in select * from jsonb_array_elements(p->'items') loop
    select * into v_prod from public.product where id = (v_item->>'product_id')::uuid;
    if v_prod.id is null then raise exception 'Producto no encontrado'; end if;
    v_unit := coalesce(nullif(v_item->>'unit', ''), 'base');
    v_factor := case when v_unit = 'pack' then v_prod.pack_size else 1 end;
    if coalesce((v_item->>'quantity')::numeric, 0) <= 0 then raise exception 'Cantidad inválida para %', v_prod.name; end if;
    -- Precio por unidad base: el digitado, o el de lista (de la presentación si existe).
    v_price := case
      when v_doc.reason <> 'venta' then null
      when nullif(v_item->>'unit_price', '') is not null then (v_item->>'unit_price')::numeric / v_factor
      when v_unit = 'pack' then coalesce(v_prod.price_pack, v_prod.price * v_prod.pack_size) / v_prod.pack_size
      else v_prod.price end;
    perform internal.apply_line(v_doc, v_prod.id, -((v_item->>'quantity')::numeric * v_factor), null, v_price,
      (v_item->>'quantity')::numeric, case when v_unit = 'pack' then v_prod.pack_unit else v_prod.unit end);
  end loop;
  return internal.close_doc(v_doc.id);
end $$;

-- -----------------------------------------------------------------------------
-- Conteo físico: fija el stock contado y registra la diferencia como ajuste.
-- p: { note?, items: [{ product_id, counted }] }  (counted en unidad base). Devuelve null si nada cambió.
-- -----------------------------------------------------------------------------
create or replace function internal.register_count(p jsonb, p_user uuid) returns public.stock_doc language plpgsql as $$
declare
  v_doc public.stock_doc;
  v_item jsonb;
  v_prod public.product;
  v_counted numeric;
begin
  insert into public.stock_doc (kind, reason, note, user_id, created_at)
  values ('ajuste', 'conteo', nullif(trim(p->>'note'), ''), p_user, coalesce((p->>'created_at')::timestamptz, now()))
  returning * into v_doc;
  for v_item in select * from jsonb_array_elements(coalesce(p->'items', '[]')) loop
    select * into v_prod from public.product where id = (v_item->>'product_id')::uuid for update;
    v_counted := (v_item->>'counted')::numeric;
    if v_prod.id is null or v_counted is null then continue; end if;
    if v_counted < 0 then raise exception 'El conteo de % no puede ser negativo', v_prod.name; end if;
    if v_counted <> v_prod.stock then
      perform internal.apply_line(v_doc, v_prod.id, v_counted - v_prod.stock, null, null, v_counted, v_prod.unit);
    end if;
  end loop;
  if not exists (select 1 from public.stock_movement where doc_id = v_doc.id) then
    delete from public.stock_doc where id = v_doc.id;
    return null;
  end if;
  return internal.close_doc(v_doc.id);
end $$;

create or replace function public.inv_entry(p jsonb) returns public.stock_doc
language plpgsql security definer set search_path = public as $$
begin
  perform internal.assert_staff();
  return internal.register_entry(p - 'created_at', auth.uid());
end $$;

create or replace function public.inv_exit(p jsonb) returns public.stock_doc
language plpgsql security definer set search_path = public as $$
begin
  perform internal.assert_staff();
  return internal.register_exit(p - 'created_at', auth.uid());
end $$;

create or replace function public.inv_count(p jsonb) returns public.stock_doc
language plpgsql security definer set search_path = public as $$
begin
  perform internal.assert_staff();
  return internal.register_count(p - 'created_at', auth.uid());
end $$;

-- Anular un documento: revierte sus líneas (el costo promedio no se recalcula). Solo administradores.
create or replace function public.inv_void_doc(p_doc uuid, p_reason text) returns public.stock_doc
language plpgsql security definer set search_path = public as $$
declare
  v_doc public.stock_doc;
  v_rev public.stock_doc;
  r record;
begin
  perform internal.assert_admin();
  if nullif(trim(p_reason), '') is null then raise exception 'Indica el motivo de la anulación'; end if;
  select * into v_doc from public.stock_doc where id = p_doc for update;
  if v_doc.id is null then raise exception 'Documento no encontrado'; end if;
  if v_doc.voided_at is not null then raise exception 'El documento ya está anulado'; end if;
  -- Las líneas de reversa se registran en un ajuste propio para que el kardex cuadre.
  insert into public.stock_doc (kind, reason, reference, note, user_id)
  values ('ajuste', 'otro', 'Anula #' || v_doc.number, 'Anulación de ' || v_doc.kind || ' #' || v_doc.number || ': ' || trim(p_reason), auth.uid())
  returning * into v_rev;
  for r in select product_id, quantity, unit_cost from public.stock_movement where doc_id = p_doc loop
    perform internal.apply_line(v_rev, r.product_id, -r.quantity, null, null, -r.quantity, null);
  end loop;
  perform internal.close_doc(v_rev.id);
  update public.stock_doc set voided_at = now(), voided_by = auth.uid(), void_reason = trim(p_reason) where id = p_doc returning * into v_doc;
  return v_doc;
end $$;

-- -----------------------------------------------------------------------------
-- Vistas
-- -----------------------------------------------------------------------------
create view public.product_stock with (security_invoker = true) as
select p.*,
       c.name as category_name, c.color as category_color, s.name as supplier_name,
       round(p.stock * p.cost, 2) as value_cost,
       round(p.stock * p.price, 2) as value_price,
       case when p.price > 0 then round((1 - p.cost / p.price) * 100, 1) end as margin,
       (p.stock <= 0) as is_out,
       (p.stock > 0 and p.stock <= p.min_stock) as is_low,
       m.last_entry_at, m.last_exit_at
from public.product p
left join public.category c on c.id = p.category_id
left join public.supplier s on s.id = p.supplier_id
left join lateral (
  select max(created_at) filter (where quantity > 0) as last_entry_at,
         max(created_at) filter (where quantity < 0) as last_exit_at
  from public.stock_movement where product_id = p.id
) m on true;

-- Listas con nombre del usuario (corren como dueño para leer staff; filtran por personal activo).
create view public.doc_list as
select d.*, su.name as supplier_name, nullif(concat_ws(' ', st.first_name, st.last_name), '') as user_name
from public.stock_doc d
left join public.supplier su on su.id = d.supplier_id
left join public.staff st on st.user_id = d.user_id
where internal.is_staff();

create view public.movement_list as
select m.*, d.number as doc_number, d.kind, d.reason, d.reference, d.party, d.voided_at, d.user_id,
       p.code, p.name as product_name, p.brand, p.model, p.unit,
       nullif(concat_ws(' ', st.first_name, st.last_name), '') as user_name
from public.stock_movement m
join public.stock_doc d on d.id = m.doc_id
join public.product p on p.id = m.product_id
left join public.staff st on st.user_id = d.user_id
where internal.is_staff();

create or replace function public.inv_doc(p_doc uuid) returns jsonb
language plpgsql stable security definer set search_path = public as $$
begin
  perform internal.assert_staff();
  return (select to_jsonb(d) || jsonb_build_object(
    'lines', (select coalesce(jsonb_agg(to_jsonb(m) || jsonb_build_object('code', p.code, 'product_name', p.name, 'brand', p.brand, 'model', p.model, 'unit', p.unit)
                                        order by p.name), '[]')
              from public.stock_movement m join public.product p on p.id = m.product_id where m.doc_id = d.id))
    from public.doc_list d where d.id = p_doc);
end $$;
